### ISSUE TITLE
decide about how to treat `p`s that stretch over `pb`s (in data and in app), e.g. in doc 0030

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-data#120]

**Comment by timofruehwirth** [comment]
@linxOD , we have used the `<p prev="true">` solution now for docs 0030, 0031, 0053, 0063.
for the prose documents, we will do this as soon as we have updated the ODD for prose container structure.

**Comment by linxOD** [comment]
odd updated
