### ISSUE TITLE
reuse of @ana(s)

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-data#128]
We tend to use the same @ana(s) for `InterpGrp` that we have already introduced elsewhere. Is it possible to fetch the data?
For instance the first time #ana_003 appears is in doc 0058 and we reuse it in doc0063, could you please enable this option?

**Comment by linxOD** [comment]
In this case please add document id like this:
amp-transcript__0058.xml#ana_003
