### ISSUE TITLE
Re: 'mentioned in papers' category 

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-data#140]
"Mentioned in papers" includes two columns of numbers: the left one indicates "how many times the entity/ies appear(s)" and the right one shows "the number of entities that share this number".
Can we think of a way to make it more user-friendly/intuitive?

![image](https://github.com/Auden-Musulin-Papers/amp-data/assets/42061592/e34b4fad-3f99-4db8-be87-8653a6b718a8)

**Comment by linxOD** [comment]
The column 'mentioned in papers #' tells you: 
* In how many documents a e.g. person is mentioned.
* The Filter above the table summarizes the column and tells you how many persons are mentioned in e.g. 3 Papers.

If you do not find this filter usefull can I remove it?
