### ISSUE TITLE
Adding PID to teiHeader Persons 

### ISSUE THREAD

**Issue by linxOD** [Auden-Musulin-Papers/amp-data#141]
e.g. author, editor, editionStmt name

**Comment by timofruehwirth** [comment]
@linxOD , what follows from this? - what do we have to change (and how) in the XMLs?

**Comment by linxOD** [comment]
as discussed there is a file called [preprocess.xsl](https://github.com/Auden-Musulin-Papers/amp-data/blob/dev/xsl/preprocess.xsl)
please verify ORCID or GND especially for authors
