### ISSUE TITLE
ODD elements required for comments in `interp`

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-data#144]
- [x] `citedRange` in `bibl` within `desc` (optional) (e.g., doc 0071)
    - [x] if `citedRange` , must have @unit , @from , and @to="13" (required)
- [x] `stamp` in `desc` (optional) (e.g., doc 0057)
- [x] `bibl` in `event` within `listEvent` in `desc` (optional) (e.g., doc 0039) (@linxOD)
    - [x] `msIdentifier` within `bibl` (as in doc 0039)
- [x] `orig` and `reg` (both optional) within `choice` (optional) within `seg` (e.g., doc 0009)
- [x] `<rs type="person" ref="#amp_person_155 #amp_person_171" ana="acdh:amp-transcript__0009.xml#ana_012">Langers</rs>` in doc0044
- [x] `<rs type="note" ana="acdh:amp-transcript__0009.xml#ana_012">` in doc0010
- [x] allow `rs type="note"` within transcription
- [x] `orig` and `reg` (both optional) within `choice` (optional) within `desc` (e.g., doc 0053)

**Comment by linxOD** [comment]
added to odd, note: `citedRange` cannot appear in `desc` as standalone element. It must be contained by either `bibl` or `biblStruct`

**Comment by linxOD** [comment]
added to odd, note: `citedRange` cannot appear in `desc` as standalone element. It must be contained by either `bibl` or `biblStruct`

**Comment by linxOD** [comment]
bcfdeb750d7b7eb46a47da47479f7367ff7a0f4e

**Comment by timofruehwirth** [comment]
`citedRange` within `bibl` does still not validate e.g. in doc 0004

**Comment by linxOD** [comment]
> `citedRange` within `bibl` does still not validate e.g. in doc 0004

please make sure you are in the correct branch "dev"

**Comment by linxOD** [comment]
> * [ ]  `bibl` in `event` within `desc` (optional) (e.g., doc 0004)

`bibl` can't be contained by `event` and `event` can't be contained by `desc`
However, `<desc><bibl><event/></bibl></desc>` works.

**Comment by linxOD** [comment]
> value of @ana when referring to interp in another document, e.g., ana="amp-transcript__0009.xml#ana_012" in doc 0044, or should this also refer to the id.acdh namespace?

please always use the namespace `acdh:`
but make sure you added the `prefixDef` template I sent.

**Comment by timofruehwirth** [comment]
re branch:
we are working on dev06 (as before on dev04 and dev05) and will finish working on this branch by mid-February;
please let's communicate next time before changing naming conventions to prevent any parallel branching ...

**Comment by timofruehwirth** [comment]
> > value of @ana when referring to interp in another document, e.g., ana="amp-transcript__0009.xml#ana_012" in doc 0044, or should this also refer to the id.acdh namespace?
> 
> please always use the namespace `acdh:` but make sure you added the `prefixDef` template I sent.

still doesn't validate, but - I guess - bc we are working on different branches ...?

**Comment by linxOD** [comment]
> re branch: we are working on dev06 (as before on dev04 and dev05) and will finish working on this branch by mid-February; please let's communicate next time before changing naming conventions to prevent any parallel branching ...

As informed some weeks ago. No branch other than `dev` is part of the main workflow. If you still like to use additional branches then merging smaller changes with `dev` is the way to go.
