### ISSUE TITLE
prepare getting AMP edition into LoC and BL catalogs

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-data#147]
- [x] find out who to get in touch with regarding ingestion of edition into catalog (e-mail addresses)
    - [x] Library of Congress
    - [x] British Library
- [ ] draft e-mail to them
    - [ ] our request (ingestion of edition into catalog)
    - [ ] point out catalog entries in univie, ÖAW, and Verbund catalogs, with links

**Comment by demigrigo** [comment]
>https://knowledge.exlibrisgroup.com/Content/Knowledge_Articles/Primo/Knowledge_Articles/Library_of_Congress_Digital_Collections_in_CDI 

Email: Collection Development Office (cdo@loc.gov)

There is also: "ask a librarian"

**Comment by demigrigo** [comment]
Re: British Library; I wrote to them on Twitter and on "bl_ref_services@bl.uk"
