### ISSUE TITLE
pls rename value "italics" (of @rend used in `hi`) to "italic

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-data#149]

**Comment by linxOD** [comment]
could you specify where to change this value? Is this an app or data issue?

**Comment by timofruehwirth** [comment]
it's a data issue, so that the value validates against the ODD; and it's an app issue, so that the display of italics works with the new correct `italic` value

**Comment by linxOD** [comment]
The app stylesheets are expecting "italic" as value and never "italics" so I am wondering how this is still part of the data?
Please add some information on the source document where this is an issue.

**Comment by timofruehwirth** [comment]
value "italic" does not yet validate, eg in doc 0053

**Comment by timofruehwirth** [comment]
works fine now, thank you
