### ISSUE TITLE
Correct pb types

### ISSUE THREAD

**Issue by linxOD** [Auden-Musulin-Papers/amp-data#159]
Please replace "nan" with correct types for:
https://github.com/Auden-Musulin-Papers/amp-data/blob/dev/data/editions/amp-transcript__0026.xml#L113
https://github.com/Auden-Musulin-Papers/amp-data/blob/dev/data/editions/amp-transcript__0026.xml#L129
https://github.com/Auden-Musulin-Papers/amp-data/blob/dev/data/editions/amp-transcript__0049.xml#L112
https://github.com/Auden-Musulin-Papers/amp-data/blob/dev/data/editions/amp-transcript__0049.xml#L133

**Comment by timofruehwirth** [comment]
pb @type fixed in docs 0026 0049
