### ISSUE TITLE
Text für `Read more` und `Description`

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-data#16]
lieber @linxOD ,

- Sandra hat einen Text geschrieben, der für eine Seite gedacht ist, zu der sowohl der `Read more`-Button als auch das `Description`-Feld verlinkt: https://github.com/Auden-Musulin-Papers/amp-background/blob/652c0f4c0b5cf2236a16a0b2539f62f49f1a005d/publications/website/website_readmore.md
- Ein passendes Foto habe ich hier angehängt.
- Was uns bei dem Foto-Karussell aufgefallen ist: Da die Fotos ungleich hoch sind, verschiebt sich auch das weiße Hintergrund-Feld je unterschiedlich weit nach unten ... vermutlich muss man die Fotos auf gleiche Höhe hin beschneiden ...
- im `Social`-Bereich auf der Startseite unten könntest du sehr gerne auch unseren Twitter-Account verlinken (@AMP_OeAW). Außerdem verlinkt das GitHub-icon momentan zum `data`-repo - besser wäre die Github-Startseite der Organisation (https://github.com/Auden-Musulin-Papers)

muchas gracias!

![DSC_0216](https://user-images.githubusercontent.com/77000983/146346371-a1ab4066-8553-4cb9-a7e1-1acba0cdfbae.JPG)

**Comment by linxOD** [comment]
partially closed with: https://github.com/Auden-Musulin-Papers/amp-data/commit/101edad067bb75b4f29689d276edb73f4b88dbf8

**Comment by csae8092** [comment]
sauber wäre es, wenn der Text von Sandra nach XML/TEI überführt (z.B mit https://oxgarage.tei-c.org/), die datei in `data/meta/description.xml` abgelegt wird und dann mittles eigenem xslt nach xhtml beim build der static-pages transformiert wird

aber ich schätze das habt ihr ohnehin so geplant gehabt

**Comment by timofruehwirth** [comment]
XML/TEI kriege ich noch heute hin ...
