### ISSUE TITLE
Prose ODD: container structure and rules

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-data#167]
-`<teiHeader>`
--`<interpGrp>` as in correspondence
-`<text type="prose" hand="#????">` required
--`<body>`
---`<div type="transcription" xml:id="transcription_amp_????" xml:lang="??">` required
----`<pb facs="https://iiif.acdh.oeaw.ac.at/amp/amp_????/" type="sheet" ed="??"/>` required
-----within `<div type="transcription" ...>`: `<space quantity="??" unit="char"/><head><hi rend="underline"><rs type="lit_work" ref="#lit_work_id_??">` all of this optional
-----within `<div type="transcription" ...>`: `<p>` **optional**
------within `p`: `<space quantity="??" unit="char"/>`, `<del>`, `<rs>`, `<high rend="????">` optional
-----within transcription `div`:`<quote source="????">` optional (at same level as `p`s) -> **this is somewhat urgent**
------within `quote`: `seg` optional, `p` optional, `ab` optional
-----`<ab>` optional (for page numbers and other non-paragraph additions)
------within `ab`: `<space quantity="??" unit="char"/>`, `<del>`, `<rs>`, `<high rend="????">` optional
-----`<p prev="true">` optional (for `p`s that stretch over a `pb` element; also if the two `p`s are interrupted by an `ab` such as for page numbers)
------within `p`: optional `seg`
-------within `seg`: optional `quote source="????"` (for `quote` same rules as in correspondence ODD), **and also `lb` and `space`**
--------within `quote`: optional `seg`, optional `lg` (for `lg` same rules as in correspondence ODD)

also:
- `<foreign xml:lang="??">` optional
- `<choice><orig>...<orig><reg>...</reg></choice>` optional
- `<quote source="acdh:amp-transcript__0043.xml">` for quotation from AMP document 0043 should link to this document

**Comment by linxOD** [comment]
unfortunately a framework can only have one schema. Two options:
* validate manually every time using Oxygen Validate -> Configure Validation Scenarios
* manually add the following tag bevore the TEI root element:
    -> `<?xml-model href="../../framework/auden-musulin/schema/out/am-prose.rng"?>`
    -> `<?xml-model href="../../framework/auden-musulin/schema/out/am-corresp.rng"?>`

**Comment by timofruehwirth** [comment]
ok, which part of the following lines do we replace with `framework/auden-musulin/...`?
```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml"
	schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
```
furthermore, if we proceed like this, how do we deal with hybrid documents (containing of a letter with envelope, but also enclosing a prose text as attachment)?

**Comment by timofruehwirth** [comment]
update:
- in the penultimate line, we have added that we optionally need "also lb and space" within `seg`
- in the 7th line, we have replaced the `title` element with the `head` element

**Comment by timofruehwirth** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="../../framework/auden-musulin/schema/out/am-prose.rng" type="application/xml"
	schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
```

**Comment by timofruehwirth** [comment]
update in 8th line: `p` within first-level `div` only optional (because we have instances where we only have `ab`s)

**Comment by timofruehwirth** [comment]
update: we would like also to have the option (not required), to have, within the main `<div type="transcription" ...`, another `div` (also in the first place, before `head`) as in the beginning of doc 0028 (where we have a stamp preceding the heading) - we have checked, it's tei-all-conformant

**Comment by timofruehwirth** [comment]
we need this update: the `<div type="transcription" ...>` can optionally also contain another `div type="prose"` (also at the very beginning), see doc 0028; and this lower-level `div` can also contain a `div` (next to paragraphs, abs etc.)

**Comment by linxOD** [comment]
doc 0028 has many problems we might want to discuss. e.g. mixing div, ab and p at same structural level.

**Comment by timofruehwirth** [comment]
- we need `div type="prose"` as wrapper for prose text proper within `div type="transcription" ...`
- we need type-less `div` (eg for stamps)
- we need `floatingText` with `body` with `div type="prose"` or `div type="letter"` or type-less `div`
+ update: `floatingText` can be wrapped within `quote` (such as for speech embedded in doc 0062)

**Comment by linxOD** [comment]
testing required:
> * we need `div type="prose"` as wrapper for prose text proper within `div type="transcription" ...`
> * we need type-less `div` (eg for stamps)
> * we need `floatingText` with `body` with `div type="prose"` or `div type="letter"` or type-less `div`

is allowed in TEI all:
> * update: `floatingText` can be wrapped within `quote` (such as for speech embedded in doc 0062)

**Comment by timofruehwirth** [comment]
update:
in both correspondence and prose, we need to markup revisions like so:
- `del` (as we have it; optionally we use it with @rend, eg `rend="overtyped")
- `add` for additions; always (required) with @place, eg `place="superimposed"` - we use the values suggested by the TEI (https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.placement.html) PLUS the value "superimposed"
- `subst` element for nesting `del` (or `gap`) together with `add` for replacements

-> so far, this has no implications for app display!

**Comment by timofruehwirth** [comment]
thank you for the update!

**Comment by timofruehwirth** [comment]
we also need `del` @rend with value "overstrike" and "overwritten"

**Comment by timofruehwirth** [comment]
thank you, everything works

**Comment by timofruehwirth** [comment]
update: we need `g` inside `l` and `p`; we need `glyph` (with `desc` inside) within `charDecl` within `encodingDesc`
in diesem Zusammenhang noch eine wichtige Frage: können wir von `g ref="# ...` auf ein `glyph` verweisen, das im Header eines anderen Dokuments steht? (so wie bei den Kommentaren auch ...)

further update: we need value "whiteout" for @rend in `del` in correspondence and prose

**Comment by linxOD** [comment]
Bei einem Kommentar macht es durchaus Sinn auf ein anderes Dokument zu verweisen. Jedoch würde ich Glyphs duplizieren und in jedem Dokument alle Glyphs darstellen, die im Transkript verwendet werden.

**Comment by timofruehwirth** [comment]
update: we also need value "metamark" for @rend in `del` in prose and correspondence
