### ISSUE TITLE
to be discussed: how mark up longer added (!) underlines

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-data#173]
eg doc 0043, 4r:

![image](https://github.com/Auden-Musulin-Papers/amp-data/assets/77000983/3167f402-c840-4942-b6ae-8a818511f2b9)

**Comment by timofruehwirth** [comment]
same also doc 0062, 9r

**Comment by linxOD** [comment]
see https://github.com/Auden-Musulin-Papers/amp-app/issues/213#event-13402925508
