### ISSUE TITLE
Problem with validation doc 0038

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-data#175]
Doc0038 line198 The schema complains about the addition of a <div type="poem">; it doesn't want the head

![image](https://github.com/Auden-Musulin-Papers/amp-data/assets/42061592/6225e881-9f2c-4996-ad26-4d829440a15e)

**Comment by linxOD** [comment]
make sure u use the correct schema for validation. 
e.g. corresp for letters
e.g. prose for prose

**Comment by demigrigo** [comment]
works now, thanks!
