### ISSUE TITLE
add new value in rend

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-data#177]
we would like to add a new value for <hi rend= "superscript">  and it should show as superscript
take a look at doc0028 line 266 "published1"

**Comment by demigrigo** [comment]
we would like to have a new value for 'del' and that is to have 'del rend="overlaid' every time the writer deletes the passage by adding a new piece of paper; take a look at doc0028 p3r

**Comment by timofruehwirth** [comment]
`del rend="overlaid"`
`hi rend="superscript"` -> hochgestellte Darstellung

**Comment by demigrigo** [comment]
also `del rend='edited'`
