### ISSUE TITLE
in doc 0039 we have updated the markup

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-data#178]
Please take a look at this new adaptation: https://github.com/Auden-Musulin-Papers/amp-data/blob/745905d962435f568f852a8d7b985a464a7f60d3/data/editions/amp-transcript__0039.xml#L317

let us know if it can be done something regarding the website presentation :)

**Comment by linxOD** [comment]
please check the latest commit if thats how it should look

**Comment by demigrigo** [comment]
it works now :)
