### ISSUE TITLE
change in attributes in `text` and `div type="transcription"` for both correspondence and prose ODDs

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-data#179]
- [x] we would like to transfer the overall `hand` attribute from `text` node to `div type="transcription"` (so that no @hand is required anymore for `text`)
- [ ] if the `type` attribute in `text` node is not necessary for your web-application workflow, we would like to get rid of it

**Comment by linxOD** [comment]
* moving `@hand` to `div@transcription` is not a big problem but needs some rework in the app. (FYI: `@hand` is already allowed in any `div`
* removing `@type=prose or letter ...` from `text` has several implications:
  * there are two ODDs hence different strucutres and I need some variable to differentiate. Currently, I use text@type to identify the different strucutres for the app.
  * for creating ARCHE metadata I use text@type to divide facsimiles from photos

If you want to remove the type I needs some replacement for identifying the content (prose, letter, photo) of the XML.

**Comment by timofruehwirth** [comment]
document type (`letter`, `prose`, `photo`) in first `div` that follows after `div type="transcription"`

**Comment by linxOD** [comment]
please check your structures again. div@type=letter is not always the first in letters. div@type=envelope is often the first div after transcription.
