### ISSUE TITLE
pls find out whether persons in our Baserow table have an entry in PMB ...

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-data#181]
... and, if yes, please insert PMB link (like https://pmb.acdh.oeaw.ac.at/entity/3220/)  into PMB column of person entity in Baserow; please check for all persons in Baserow

**Comment by linxOD** [comment]
This list is generated for the import to PMB. Only persons with a GND are considered. 
The import to PMB is done by Peter. 
https://github.com/Auden-Musulin-Papers/amp-entities/blob/main/out/beacon.txt

I extended the wikidata enriching for baserow to include the PMB ID.

**Comment by timofruehwirth** [comment]
super thanks done
