### ISSUE TITLE
Diplomatic transcription (eg Telegram W. H. Auden to Stella Musulin 1971-05-13) does not show multiple spaces

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-data#19]

**Comment by csae8092** [comment]
white-space is a tricky thing in XML and XSL processing; therefore I'd either ignore it if there is not much significance in extra white-spaces or explicitly encode extra large spaces (or gaps) in the transcription. 
* as of now, the XSL Processing acutally does preserve the whitespace; but the (default) css for whitespace removes those; this can be changed by e.g. settings `<body class="page" style="white-space:pre">` but this should be tested carefully as this might need some changes in the XML/TEI Markup as well; e.g. 
```xml
<p>
        MUSULIN NEULINGGASSE  26/14  1030/WIEN
</p>
<p>
        =  KOMMEN SAMSTAG =  LOVE  WYSTAN
 </p>
 would then be rendered WITH the white-spaces and linebreaks following and preceding the `<p>`

**Comment by timofruehwirth** [comment]
how can white-space be encoded explicitly in XML?
w/ unicode space character (u+0020)?

**Comment by csae8092** [comment]
> how can white-space be encoded explicitly in XML? w/ unicode space character (u+0020)?

I'd (ab)use some TEI-Element, e.g. `gap`; but I'd do this only if I intent to use this information for some research questions/queries, like give me all paragraphs containing this phenomena because this may be important to answer some research questions;
I'd not bother about those white spaces only to make the html representation look similar to the source. If I want to know how the source looked like, I'd look at the facsimile

**Comment by timofruehwirth** [comment]
@linxOD , können wir ja morgen im meet-up besprechen. passt wieder 11 Uhr morgen? link ist wieder: https://teams.microsoft.com/l/meetup-join/19%3a7acce896e5404e32be20117e86c3d0b8%40thread.tacv2/1641202329895?context=%7b%22Tid%22%3a%22ef12f07e-2409-490f-8edc-3bc91a927a71%22%2c%22Oid%22%3a%223da06316-b2a7-4888-a6f2-cef1cbe6786f%22%7d

**Comment by timofruehwirth** [comment]
`<space>` passt von der Definition her auch nicht ganz (`This element should be used wherever it is desired to record an unusual space in the source text, e.g. space left for a word to be filled in later, for later rubrication, etc. It is not intended to be used to mark normal inter-word space or the like.`), aber aus meiner Sicht vielleicht noch passender als `<gap>` ...

**Comment by timofruehwirth** [comment]
there was also a related discussion on the mattermost x-technologies channel earlier today, https://mattermost.acdh.oeaw.ac.at/acdh/pl/czhx71z5q3br8jbbop785bz5je

**Comment by timofruehwirth** [comment]
problem solved: we will use `<space>` element to mark additional spaces in typescripts
