### ISSUE TITLE
Mark up letter documents 0014-0025, 0030-0031, 0034, 0041, 0044-0045, 0053, 0057-0061, 0063

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-data#93]
Workflow:
- [ ] check branch of `amp-data` - work only on `dev05` branch
- [ ] open working copy of XML file in question: you find working copies in `tmp` folder of `data` folder in `amp-data`, file names are `amp-transcript__0XXX-copy.xml` (only work on working copies)
- [ ] have letter-pattern open on screen (https://mattermost.acdh.oeaw.ac.at/acdh/pl/g85t19rw7jy38rnc8835ecuhao)
- [ ] mark up letters in compliance with letter pattern - if there is any doubt, please ask right away
- [ ] update `revisionDesc` as in documents that we have already updated
- [ ] after finishing markup, in Oxygen select Document/Validate/Validate
- [ ] check if valid in bottom bar ("Validation successful")
- [ ] if "Validation failed", recheck and correct
- [ ] save and push
- [ ] collate with @timofruehwirth or @Mayers1907 with Oxygen Compare Files tool

**Comment by demigrigo** [comment]
doc0018 in letter_message in the `<address>` part I added `<persName>` so that Spender's name could be accepted as correct

**Comment by demigrigo** [comment]
doc0021 in `div type="envelope`, the `address` part cannot contain `unclear` values; we might need to fix this. What I did as of now I included the unclear punctuation mark inside the `rs`. Having the puctuation mark outside of the `rs` without the `unclear` was also problematic

**Comment by demigrigo** [comment]
doc0022 in the `opener` section `address` cannot include any punctuation marks followed the `rs`; therefore, I enclosed the fullstop within the `rs` as in:
`             <address>
                <rs type="place" ref="#amp_place_id_11"><hi rend="underline">Wien III</hi><lb/>
                 Neulingasse 26.</rs>
                 </address>
`

**Comment by demigrigo** [comment]
doc0023, 0024, 0025 there is not `salute`

doc0053 there is not `closer`

**Comment by demigrigo** [comment]
we need to be consistent with `seg type=` or `seg hand=`; from 0014 onwards I used `seg hand=`

**Comment by demigrigo** [comment]
shall we differentiate `<signed hand="#handwritten>`  (ex. doc21)  vs `<signed hand="#typed">` (ex. doc30)

**Comment by demigrigo** [comment]
doc0031

- added the element of `quote` where Stella cites Auden

**Comment by demigrigo** [comment]
doc0058 the structure of the letter violates the position of `opener`

**Comment by demigrigo** [comment]
doc0006 and doc0060 need to be doublechecked because of the `strings` in `opener`

**Comment by demigrigo** [comment]
doc0061 
- we have two `placeName` s and one `affiliation` in `opener`
- there are two types of `signed`

**Comment by demigrigo** [comment]
doc0034

- find a way to mark up the letter headers
- find a way to mark up the telephone numbers
- dont forget to attach the attributes `hand` in `signed`
