### ISSUE TITLE
updates to ODD

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-data#94]
Hello! We would like some updates for ODD schema:

- [x] in doc 0009: we added `<addrLine>℅ <rs type="person" ref="#amp_person_19">Heyworth</rs></addrLine>`  in the `address` which is part of the `opener`
- [x] we would like to have `salute` (ex 0024) and `signed` (ex 0031) as optional  part of the `closer`  (ex 0024)
- [x] we would to add `hand ="#typed|#handwritten"` in the `div type="poem"` (ex 0042)
- [x] could you please activate `cb`  (ex 0042)?
- [x] we would like to enable us the`<space quantity="...." unit="char"/>`  before `date` of the `dateline` (as part of the `address`), and before `signed`, `salute` of the `closer`  (ex 0031)
- [x] we would like to have the attribute `hand ="#typed|#handwritten"` in `signed`  (ex 0021)
- [x] `origPlace` in `origin` node
- [x]  `district`  in node  `address` which part of  `correspDesc` 
- [x] `persName` within `opener`
- [x] <del>`head` must work also after `lg` as in data/editions/amp-transcript__0040.xml line 260</del>
- [x] `closer` can include two (!) `salute` elements (both can be followed by `lb/`) - as in data/editions/amp-transcript__0034.xml and data/editions/amp-transcript__0060.xml
- [x] `signed` element can (optionally!) be followed by an `lb/` - as in data/editions/amp-transcript__0070.xml and data/editions/amp-transcript__0034.xml
- [x] `correspDesc` must include at least one `correspAction`
- [x] `correspAction` must have `@type` attribute; possible values (only these are permitted) are `sent`, `transmitted`, `redirected`, and `received`
- [x] `correspAction` can (optionally) contain the following elements: `persName`, `orgName`, `placeName`, `date`
- [x] we will change to using `notBefore-iso` and `notAfter-iso` (formats used will be like "1964-12-23" for dates, but also "1964-12-23T14:00:01+01:00" date-time combinations) -> format checked in ODD

Thank you * - *

**Comment by demigrigo** [comment]
Additional comments:

- [x] we added `space` before the `addrLine` (ex 0034)
- [x] we added `space` before the `date` in `dateLine `(ex 0053)

**Comment by linxOD** [comment]
updated
if Oxygen does not show any errors like for `space` before addrLine` aso. there is not additional rule required.

**Comment by demigrigo** [comment]
hello! 

- [x] could you please active `space` before `signed` (ex. 0060)?
- [x] please make optional `salute` and `lb` in `closer`   (ex. 0058)?
- [x] please make optional `closer` (ex. 0060)?


in 0061 there are two `<div type="letter_messages">` and <div type="opener"> could you please update the schema accordingly?

**Comment by demigrigo** [comment]
- [x] please add `space` before the `salute` 

thank you!

**Comment by linxOD** [comment]
> head must work also after lg as in data/editions/amp-transcript__0040.xml line 260

this is not tei_all data conform.
